/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectout1cperales;

import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clara
 */
public class ModificarPedido extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPedido
     */
    private JTable tabla;
    private Object[] datosFila;
    private int filaSeleccionada;
    private Connection con;
    private String empleadoS;
    private Object[] empleados;
    
    public ModificarPedido() {
        initComponents();
    }
    
    public ModificarPedido(JTable tabla, Object[] datosFila, int filaSeleccionada, Connection con){
        this.tabla = tabla;
        this.datosFila = datosFila;
        this.filaSeleccionada = filaSeleccionada;
        this.con = con; // Guardamos la conexión
        initComponents();
        
        String sql = "SELECT nombre FROM Empleados";

        // Crear un arreglo con los JRadioButton
        JRadioButton[] radioButtons = { jRadioButton1, jRadioButton2, jRadioButton3, 
                                        jRadioButton4, jRadioButton5, jRadioButton6, 
                                        jRadioButton7, jRadioButton8, jRadioButton9 };

        try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            int i = 0; // Contador para iterar sobre los radioButtons
            while (rs.next() && i < radioButtons.length) {  // Iterar sobre los resultados y los radio buttons
                String nombre = rs.getString("nombre");

                // Cambiar el texto del JRadioButton correspondiente
                radioButtons[i].setText(nombre);
                if (radioButtons[i].getText().equals(datosFila[9].toString()))
                {
                    radioButtons[i].setSelected(true);
                }

                i++;  // Incrementar el índice
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        sql = "SELECT nombre FROM Ciudades";
        try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            int i = 0;
            while (rs.next()){
                String nombre = rs.getString("nombre");
                jComboBox1.addItem(nombre);
                if (nombre.equals(datosFila[7].toString()))
                {
                    jComboBox1.setSelectedIndex(i);
                }
                i++;
            }
        }
        catch (SQLException e){
            e.printStackTrace();
        }
        
        sql = "SELECT nombre FROM CompEnvios";
        DefaultListModel<String> listModel = new DefaultListModel<>();
        try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            int i = 0;
            while (rs.next()){
                String nombre = rs.getString("nombre");
                listModel.addElement(nombre);
                i++;
            }
            jList1.setModel(listModel);
            for (int j = 0; j < listModel.getSize(); j++){
                if (listModel.getElementAt(j).equals(datosFila[8].toString())) {
                    jList1.setSelectedIndex(j);
                    break;
                }
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        
        jTextField1.setText(datosFila[1] != null ? datosFila[1].toString() : ""); // Dirección
        jTextField2.setText(datosFila[2] != null ? datosFila[2].toString() : ""); // Código postal
        jTextField3.setText(datosFila[3] != null ? datosFila[3].toString() : ""); // Cargo
        jTextField4.setText(datosFila[4] != null ? datosFila[4].toString() : ""); // Fecha de pedido
        jTextField5.setText(datosFila[5] != null ? datosFila[5].toString() : ""); // Fecha de envio
        jTextField6.setText(datosFila[6] != null ? datosFila[6].toString() : ""); // Fecha de entrega
        jTextField10.setText(datosFila[10] != null ? datosFila[10].toString() : ""); // Compañia de cliente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 2147483647));
        setMinimumSize(new java.awt.Dimension(900, 0));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton3.setText("Seleccionar cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección:"));
        jPanel2.add(jTextField1);

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cod postal:"));
        jPanel2.add(jTextField2);

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo:"));
        jPanel2.add(jTextField3);

        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de pedido:"));
        jPanel2.add(jTextField4);

        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de envío:"));
        jPanel2.add(jTextField5);

        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de entrega:"));
        jPanel2.add(jTextField6);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudad:"));
        jPanel3.add(jComboBox1);

        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1);

        jTextField10.setEditable(false);
        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente:"));
        jPanel3.add(jTextField10);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado:"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        jPanel4.add(jRadioButton1, new java.awt.GridBagConstraints());

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton3");
        jPanel4.add(jRadioButton2, new java.awt.GridBagConstraints());

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton4");
        jPanel4.add(jRadioButton3, new java.awt.GridBagConstraints());

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jRadioButton4, gridBagConstraints);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jRadioButton5, gridBagConstraints);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("jRadioButton7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jRadioButton6, gridBagConstraints);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("jRadioButton8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jRadioButton7, gridBagConstraints);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("jRadioButton9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jRadioButton8, gridBagConstraints);

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("jRadioButton6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jRadioButton9, gridBagConstraints);

        jPanel3.add(jPanel4);

        jLabel1.setText("C. de envío:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Obtener los datos modificados de los JTextField
    String direccion = jTextField1.getText();
    String codigoPostal = jTextField2.getText();
    String cargo = jTextField3.getText();
    String fechaPedido = jTextField4.getText();
    String fechaEnvio = jTextField5.getText();
    String fechaEntrega = jTextField6.getText();
    String ciudad = (String) jComboBox1.getSelectedItem();
    String companiaEnvio = jList1.getSelectedValue();
    String empleado = empleadoS;
    if (buttonGroup1.getSelection() != null) {
        JRadioButton[] radioButtons = new JRadioButton[9];
        radioButtons[0] = jRadioButton1;
        radioButtons[1] = jRadioButton2;
        radioButtons[2] = jRadioButton3;
        radioButtons[3] = jRadioButton4;
        radioButtons[4] = jRadioButton5;
        radioButtons[5] = jRadioButton6;
        radioButtons[6] = jRadioButton7;
        radioButtons[7] = jRadioButton8;
        radioButtons[8] = jRadioButton9;

        for (int i = 0; i < 9; i++) {
            if (radioButtons[i].isSelected()) {
                empleado = radioButtons[i].getText();
                break;
            }
        }
    }
    
    String cliente = jTextField10.getText();
    
    // Filtro de ciudad
    

    // Definir el formato de fecha esperado
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    // Formatear las fechas si es necesario
    try {
            Date parsedFechaPedido = dateFormat.parse(fechaPedido);
            Date parsedFechaEnvio = dateFormat.parse(fechaEnvio);
            Date parsedFechaEntrega = dateFormat.parse(fechaEntrega);

            // Ahora las fechas están en el formato correcto
            fechaPedido = dateFormat.format(parsedFechaPedido);
            fechaEnvio = dateFormat.format(parsedFechaEnvio);
            fechaEntrega = dateFormat.format(parsedFechaEntrega);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Debe ser yyyy-MM-dd.");
            return;  // No continuar si hay error de formato
        }

        // Primero, actualizar la fila en el JTable original con los nuevos valores de los JTextField
        // Utilizamos el modelo de la tabla para actualizar solo la fila seleccionada
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        
        int codigoPedido = (int) model.getValueAt(filaSeleccionada, 0);
        
        model.setValueAt(direccion, filaSeleccionada, 1); // Dirección
        model.setValueAt(codigoPostal, filaSeleccionada, 2); // Código Postal
        model.setValueAt(cargo, filaSeleccionada, 3); // Cargo
        model.setValueAt(fechaPedido, filaSeleccionada, 4); // Fecha de Pedido
        model.setValueAt(fechaEnvio, filaSeleccionada, 5); // Fecha de Envío
        model.setValueAt(fechaEntrega, filaSeleccionada, 6); // Fecha de Entrega
        model.setValueAt(ciudad, filaSeleccionada, 7); // Ciudad
        model.setValueAt(companiaEnvio, filaSeleccionada, 8); // Compañía de Envío
        model.setValueAt(empleado, filaSeleccionada, 9); // Empleado
        model.setValueAt(cliente, filaSeleccionada, 10); // compañia cliente

        // Ahora, actualizamos los datos en la base de datos
        try {
            String query = "UPDATE PEDIDOS p " +
                   "SET p.DIRECCION = ?, " +
                   "    p.CODPOSTAL = ?, " +
                   "    p.CARGO = ?, " +
                   "    p.FECHAPEDIDO = ?, " +
                   "    p.FECHAENVIO = ?, " +
                   "    p.FECHAENTREGA = ?, " +
                   "    p.codCiudad = (SELECT c.codigo FROM Ciudades c WHERE c.nombre = ?), " +
                   "    p.codEmpreEnvio = (SELECT ce.codigo FROM CompEnvios ce WHERE ce.nombre = ?), " +
                   "    p.codEmpleado = (SELECT e.codigo FROM Empleados e WHERE e.nombre = ?), " +
                   "    p.codCliente = (SELECT cl.codigo FROM Clientes cl WHERE cl.nomCompania = ?) " +
                   "WHERE p.codigo = ?";

            try (PreparedStatement pst = con.prepareStatement(query)) {
                // Establecer los valores de los parámetros en la consulta
                pst.setString(1, direccion);
                pst.setString(2, codigoPostal);
                pst.setString(3, cargo);
                pst.setString(4, fechaPedido);  // Fecha formateada
                pst.setString(5, fechaEnvio);   // Fecha formateada
                pst.setString(6, fechaEntrega); // Fecha formateada
                pst.setString(7, ciudad); 
                pst.setString(8, companiaEnvio);
                pst.setString(9, empleado);
                pst.setString(10, cliente);
                pst.setInt(11, codigoPedido);  // Ahora tomamos el valor de la segunda columna (índice 1) para el código de pedido

                // Ejecutar la actualización en la base de datos
                int rowsUpdated = pst.executeUpdate();

                // Comprobar si se actualizaron filas
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "El pedido se ha actualizado correctamente en la base de datos.");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el pedido en la base de datos.");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar en BD: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SeleccionarClienteDialog dialog = new SeleccionarClienteDialog(ModificarPedido.this, con);
        dialog.setModal(true);
        dialog.setVisible(true);
        

        // Obtener la compañía seleccionada y mostrarla en el JTextField
        String companiaSeleccionada = dialog.getNombreCompaniaSeleccionada();
        if (companiaSeleccionada != null) {
            jTextField10.setText(companiaSeleccionada);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
